#!/usr/bin/env python

from __future__ import print_function
import os
import sys
import subprocess

sofiles = [ ]

blacklist = [
    '_LOBTree.so', '_LLBTree.so', 'cPersistence.so', '_zope_', 'cPickleCache.so',
    '_LFBTree.so', '_OOBTree.so', '_IIBTree.so', '_OLBTree.so', '_IFBTree.so',
    '_IOBTree.so', '_fsBTree.so',
]

def is_blacklisted(fn):
    for name in blacklist:
        if fn.startswith(name):
            return True
    return False


for directory in sys.argv[2:]:

    for fn in os.listdir(directory):
        if is_blacklisted(fn):
            continue
        fn = os.path.join(directory, fn)

        if not fn.endswith(".so.o"):
            continue
        if not os.path.exists(fn[:-2] + ".libs"):
            continue

        sofiles.append(fn[:-2])

# The raw argument list.
args = [ ]

for fn in sofiles:
    afn = fn + ".o"
    libsfn = fn + ".libs"

    args.append(afn)
    with open(libsfn) as fd:
        data = fd.read()
        args.extend(data.split(" "))

unique_args = [ ]
while args:
    a = args.pop()
    if a in ('-L', ):
        continue
    if a not in unique_args:
        unique_args.insert(0, a)


print('Biglink create %s library' % sys.argv[1])
print('Biglink arguments:')
for arg in unique_args:
    print(' %s' % arg)

args = os.environ['CC'].split() + \
    ['-shared', '-O3', '-o', sys.argv[1]] + \
    unique_args

sys.exit(subprocess.call(args))
